[package]
name = "pssm"
version = "0.2.0"
authors = ["ortho 'the darkness' stice <ortho.the.d.stice@gmail.com>"]

[dependencies]
ndarray = { version = "0.10", features = ["serde-1"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
bio = "*"
lazy_static = "*"
